site_name: DND Public Site

theme: material

plugins:
  - pub-obsidian:
      obsidian_dir: .obsidian

nav:
  - Home: index.md
  - General Notes: General World Notes.md
  - Characters: Characters/Character Nav.md
  - Culture: Culture/Culture Nav.md
  - Geography: Geography/Geography Nav.md
  - History: History/History Nav.md
  - Inhabitants: Inhabitants/Inhabitants Nav.md
  - Political Powers: Political Powers/Political Powers Nav.md
  - Religion: Religion/Religion Nav.md
  - Other: Unique Characteristics/Unique Characteristics Nav.md