site_name: DND Public Site

theme: material

plugins:
  - pub-obsidian:
    obsidian_dir: .obsidian

nav:
  - Home: index.md
  - General Notes: General World Notes.md
  - Characters: zz Navigation zz/Character Nav.md
  - Culture: zz Navigation zz/Culture Nav.md
  - Geography: zz Navigation zz/Geography Nav.md
  - History: zz Navigation zz/History Nav.md
  - Inhabitants: zz Navigation zz/Inhabitants Nav.md
  - Political Powers: zz Navigation zz/Political Powers Nav.md
  - Religion: zz Navigation zz/Religion Nav.md
  - Other: zz Navigation zz/Unique Characteristics Nav.md