site_name: DND Public Site

theme: material

nav:
  - Home: index.md
  - General Notes: General World Notes.md
  - Characters: \!\! Navigation \!\!/Character Nav.md
  - Culture: \!\! Navigation \!\!/Culture Nav.md
  - Geography: \!\! Navigation \!\!/Geography Nav.md
  - History: \!\! Navigation \!\!/History Nav.md
  - Inhabitants: \!\! Navigation \!\!/Inhabitants Nav.md
  - Political Powers: \!\! Navigation \!\!/Political Powers Nav.md
  - Religion: \!\! Navigation \!\!/Religion Nav.md
  - Other: \!\! Navigation \!\!/Unique Characteristics Nav.md