site_name: DND Public Site

theme: material

nav:
  - Home: Welcome.md
  - General Notes: General World Notes.md
  - Characters: IGNORE THIS/Character Nav.md
  - Culture: IGNORE THIS/Culture Nav.md
  - Geography: IGNORE THIS/Geography Nav.md
  - History: IGNORE THIS/History Nav.md
  - Inhabitants: IGNORE THIS/Inhabitants Nav.md
  - Political Powers: IGNORE THIS/Political Powers Nav.md
  - Religion: IGNORE THIS/Religion Nav.md
  - Other: IGNORE THIS/Unique Characteristics Nav.md