name: Deploy DND website via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --config-file mkdocs.yml

  deploy_mkdocs:
    needs: build_mkdocs
    environment:
      name: github-pages
      url: 
